### ISSUE TITLE
How to switch engine 

### ISSUE THREAD

**Issue by jameslope** [Auzgame/userscripts#18]
hi sir can you help me to switch an engine using a maia chess this is a link sir https://github.com/CSSLab/maia-chess

**Comment by Auzgame** [comment]
Unfortunately I can't do anything here. Their Chess engine is written in python and it would have to be implemented in JavaScript. Since it's not in JavaScript I can't do anything on my end. The creators of the engine would have to rewrite their bot in JavaScript or you'd have to setup a server that can interpret input and output to the bot.
